################################################################################
#                              Hexo Configuration                              #
################################################################################

################################################################################
#                                   基礎配置                                   #
################################################################################

# 網站配置
title: ㄅㄆㄇㄈ                                                                 # 標題
subtitle: bopomofo                                                              # 標題
description: 丟掉幻想  準備鬥爭                                                 # 描述
keywords:                                                                       # 鍵詞
author: 刘汲桐                                                                  # 作者
language: zh-CN                                                                 # 語言
timezone: Asia/Shanghai                                                         # 時區

# 網址配置
url: https://sulfurandcu.github.io/sulfurandcu.io/                              # 網址
root: /sulfurandcu.io/                                                          # 網站根目錄
permalink: :id.html #:year/:month/:title.html                                   # 文章鏈接的格式
permalink_defaults:                                                             # 文章鏈接缺省值
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# 目錄配置
source_dir: source                                                              # 資源文件夾，存放網站的所有資源
public_dir: public                                                              # 發佈文件夾, 存放生成的站點文件
tag_dir: tags                                                                   # 標籤文件夾, 實際存放在source/tags中
archive_dir: archives                                                           # 歸檔文件夾, 實際存放在source/archives中
category_dir: categories                                                        # 分類文件夾, 實際存放在source/categories中
code_dir: downloads/code                                                        # 代碼文件夾, 默認存放在downloads/code
i18n_dir: :lang                                                                 # 國際化目錄, 默認跟language相同
skip_render: [google**, baidu_verify_**]                                        # 不需要渲染的文件或文件夾, 放在[]中

# 文章配置
new_post_name: :title.md                                                        # 新文章的默認名稱
default_layout: post                                                            # 新文章的默認樣式
auto_spacing: false                                                             # 中文英文之間添加空格
titlecase: false                                                                # 標題首字母轉換成大寫
external_link:                                                                  # 在新標籤頁中打開網頁
  enable: true                                                                    # 使能
  field: site                                                                     # 應用到整個網站
  exclude: ''                                                                     # 除了
filename_case: 0                                                                # 把文件名稱轉換爲(0)不轉(1)小寫(2)大寫
render_drafts: false                                                            # 顯示草稿
post_asset_folder: true                                                         # 啓用Asset目錄, 文章資源目錄
marked:
  prependRoot: true
  postAsset: true
relative_link: false                                                            # 將鏈接改爲相對根目錄的相對路徑
future: true                                                                    # 顯示未來的文章
highlight:                                                                      # 代碼塊的配置
  enable: true                                                                    # 是否啓用代碼塊
  line_number: false                                                              # 是否顯示行數
  auto_detect: false                                                              # 是否自動檢測語言
  tab_replace: ''                                                                 # 是否將tab替換爲空格
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# 分類標籤
default_category: uncategorized                                                 # 默認分類
category_map:                                                                   # 分類別名
tag_map:                                                                        # 標籤別名

# 日期時間
date_format: YYYY-MM-DD                                                         # 日期格式
time_format: HH:mm:ss                                                           # 時間格式
updated_option: date                                                            # 使用文章中的日期作爲更新日期

# 分頁配置
per_page: 10                                                                    # 每頁個數 (0關閉分頁功能)
pagination_dir: page                                                            # 分頁路徑


################################################################################
#                                   擴展配置                                   #
################################################################################

# 主題配置
theme: next

# 包含排除（options only apply to the 'source/' folder）
include:
exclude:
ignore:

# Metadata elements
# https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 歸檔生成
# 插件下載：npm install --no-optional --save hexo-generator-archive
archive_generator:
  per_page: 20
  yearly: true
  monthly: true

# 標籤生成
# 插件下載：npm install --no-optional --save hexo-generator-tag
tag_generator:
  per_page: 10

# 首頁生成
# 插件下載：npm install --no-optional --save hexo-generator-index
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 部署配置
# 插件下載：npm install --no-optional --save hexo-deployer-git
deploy:
  type: git
  repo: git@github.com:sulfurandcu/sulfurandcu.io.git
  branch: main
  # - type: git
  #   repo: git@github.com:sulfurandcu/sulfurandcu.io.git
  #   branch: main
  # - type: baidu_url_submitter

# 訂閱信息
# 插件下載：npm install --no-optional --save hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true
  content_limit:
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png

search:
  path: search.xml
  field: post
  content: true
  format: html

################################################################################
#                                   網站優化                                   #
################################################################################

# 站點地圖
# 插件下載：npm install --no-optional --save hexo-generator-sitemap
# 插件下載：npm install --no-optional --save hexo-generator-baidu-sitemap
# sitemap:
#   path: sitemap.xml
# baidusitemap:
#   path: baidusitemap.xml

# 自動提交
# 插件下載：npm install --no-optional --save hexo-baidu-url-submit
# baidu_url_submit:
#   count: 1                                ## 提交最新的一個鏈接
#   host: https://sulfurandcu.github.io/    ## 在百度站長平臺中註冊的域名
#   token: ****************                 ## 請注意這是您的祕鑰，所以請不要把博客源代碼發佈在公衆倉庫裏!
#   path: baidu_urls.txt                    ## 文本文檔的地址，新鏈接會保存在此文本文檔裏
